### ISSUE TITLE
Automatic removal of Spotify listen together posts

### ISSUE THREAD

**Issue by Phalanxia** [Rodis-Infrastructure/Azalea-Archive#49]
Spotify [listen together posts](https://support.discord.com/hc/en-us/articles/115003966072-Listening-Along-with-Spotify) are large embeds which can contain inappropriate context such as text and images.
Azalea should have an option to automatically remove and log these posts.

**Comment by Archasion** [comment]
Pending PR in chrys: [#41](https://github.com/AmaranthineCodices/chrysanthemum/pull/41)
